// Generated by scripts/generate_brands.py from docs/brands/brands.json. Do not edit by hand.
package app.loyaltycards.ui.components

import app.loyaltycards.resources.Res
import app.loyaltycards.resources.brand_lidl
import app.loyaltycards.resources.brand_dm
import app.loyaltycards.resources.brand_muller
import app.loyaltycards.resources.brand_shell
import app.loyaltycards.resources.brand_ikea
import app.loyaltycards.resources.brand_mediamarkt
import app.loyaltycards.resources.brand_hm
import app.loyaltycards.resources.brand_mcdonalds
import app.loyaltycards.resources.brand_kaufland
import app.loyaltycards.resources.brand_aldi_nord
import app.loyaltycards.resources.brand_penny
import app.loyaltycards.resources.brand_rossmann
import app.loyaltycards.resources.brand_carrefour
import app.loyaltycards.resources.brand_tesco
import app.loyaltycards.resources.brand_leroy_merlin
import app.loyaltycards.resources.brand_payback
import org.jetbrains.compose.resources.DrawableResource

/** Single-color logo for a store in the catalog, or null when we don't ship one. */
internal fun brandLogo(storeId: String?): DrawableResource? = when (storeId) {
    "lidl" -> Res.drawable.brand_lidl
    "dm" -> Res.drawable.brand_dm
    "muller" -> Res.drawable.brand_muller
    "shell" -> Res.drawable.brand_shell
    "ikea" -> Res.drawable.brand_ikea
    "mediamarkt" -> Res.drawable.brand_mediamarkt
    "hm" -> Res.drawable.brand_hm
    "mcdonalds" -> Res.drawable.brand_mcdonalds
    "kaufland" -> Res.drawable.brand_kaufland
    "aldi-nord" -> Res.drawable.brand_aldi_nord
    "penny" -> Res.drawable.brand_penny
    "rossmann" -> Res.drawable.brand_rossmann
    "carrefour" -> Res.drawable.brand_carrefour
    "tesco" -> Res.drawable.brand_tesco
    "leroy-merlin" -> Res.drawable.brand_leroy_merlin
    "payback" -> Res.drawable.brand_payback
    else -> null
}
