"""Generates the store catalog and brand logo drawables from docs/brands/.

Run from the repository root after editing docs/brands/brands.json or the logos:

    python scripts/generate_brands.py

Writes:
  shared/src/commonMain/kotlin/app/loyaltycards/domain/StoreCatalogData.kt
  shared/src/commonMain/kotlin/app/loyaltycards/ui/components/BrandLogos.kt
  shared/src/commonMain/composeResources/drawable/brand_*.xml
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BRANDS = ROOT / "docs" / "brands"
SHARED = ROOT / "shared" / "src" / "commonMain"
DRAWABLES = SHARED / "composeResources" / "drawable"

# Logos we don't ship. hofer.svg is the ALDI Süd mark, which reads "ALDI", not "HOFER".
SKIPPED_LOGOS = {"hofer"}

# Card names people know these cards by, where the program name alone doesn't work.
CARD_NAME_OVERRIDES = {
    "mercator": "Mercator Pika",
    "spar": "SPAR plus",
    "dm": "dm",
    "carrefour": "Carrefour",
}

GENERIC_PROGRAM_ENDINGS = ("kartica", "kartica zvestobe", "card", "app")

HEADER = "// Generated by scripts/generate_brands.py from docs/brands/brands.json. Do not edit by hand.\n"


def card_name(brand: dict) -> str:
    """Name shown on the card, e.g. "Lidl Plus" rather than just "Lidl"."""
    if brand["id"] in CARD_NAME_OVERRIDES:
        return CARD_NAME_OVERRIDES[brand["id"]]
    program = (brand.get("loyaltyProgram") or "").strip()
    name = brand["name"]
    if (
        program
        and name.lower() in program.lower()
        and not program.lower().endswith(GENERIC_PROGRAM_ENDINGS)
        and "(" not in program
    ):
        return program
    return name


def argb(hex_color: str | None) -> str:
    if not hex_color:
        return "null"
    return "0xFF" + hex_color.lstrip("#").upper()


def kotlin_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def resource_name(brand_id: str) -> str:
    return "brand_" + re.sub(r"[^a-z0-9]", "_", brand_id.lower())


def svg_to_vector(svg: str) -> str:
    """Converts a single-path 24x24 Simple Icons SVG into an Android vector drawable."""
    paths = re.findall(r'<path[^>]*\sd="([^"]+)"', svg)
    if len(paths) != 1:
        raise ValueError(f"expected exactly one path, found {len(paths)}")
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by scripts/generate_brands.py from a Simple Icons SVG (CC0). The mark is the brand's trademark. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp"\n'
        '    android:height="24dp"\n'
        '    android:viewportWidth="24"\n'
        '    android:viewportHeight="24">\n'
        "    <path\n"
        '        android:fillColor="#FF000000"\n'
        f'        android:pathData="{paths[0]}" />\n'
        "</vector>\n"
    )


def main() -> None:
    brands = json.loads((BRANDS / "brands.json").read_text(encoding="utf-8"))

    DRAWABLES.mkdir(parents=True, exist_ok=True)
    for old in DRAWABLES.glob("brand_*.xml"):
        old.unlink()

    logo_ids = []
    for brand in brands:
        logo = brand.get("logo")
        if not logo or brand["id"] in SKIPPED_LOGOS:
            continue
        svg = (BRANDS / logo).read_text(encoding="utf-8")
        (DRAWABLES / f"{resource_name(brand['id'])}.xml").write_text(svg_to_vector(svg), encoding="utf-8", newline="\n")
        logo_ids.append(brand["id"])

    stores = []
    for brand in brands:
        stores.append(
            "        Store(\n"
            f"            id = {kotlin_string(brand['id'])},\n"
            f"            name = {kotlin_string(brand['name'])},\n"
            f"            cardName = {kotlin_string(card_name(brand))},\n"
            f"            category = {kotlin_string(brand['category'])},\n"
            f"            colorArgb = {argb(brand['primaryColor'])},\n"
            f"            secondaryColorArgb = {argb(brand.get('secondaryColor'))},\n"
            "        ),\n"
        )
    (SHARED / "kotlin/app/loyaltycards/domain/StoreCatalogData.kt").write_text(
        HEADER
        + "package app.loyaltycards.domain\n\n"
        + "internal val catalogStores: List<Store> = listOf(\n"
        + "".join(stores)
        + ")\n",
        encoding="utf-8",
        newline="\n",
    )

    cases = "".join(
        f"    {kotlin_string(brand_id)} -> Res.drawable.{resource_name(brand_id)}\n" for brand_id in logo_ids
    )
    imports = "".join(f"import app.loyaltycards.resources.{resource_name(brand_id)}\n" for brand_id in logo_ids)
    (SHARED / "kotlin/app/loyaltycards/ui/components/BrandLogos.kt").write_text(
        HEADER
        + "package app.loyaltycards.ui.components\n\n"
        + "import app.loyaltycards.resources.Res\n"
        + imports
        + "import org.jetbrains.compose.resources.DrawableResource\n\n"
        + "/** Single-color logo for a store in the catalog, or null when we don't ship one. */\n"
        + "internal fun brandLogo(storeId: String?): DrawableResource? = when (storeId) {\n"
        + cases
        + "    else -> null\n"
        + "}\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"{len(brands)} stores, {len(logo_ids)} logos")


if __name__ == "__main__":
    main()
